// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxmurihjueqlzllhusxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4bXVyaWhqdWVxbHpsbGh1c3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjcxMDIsImV4cCI6MjA2Mzg0MzEwMn0.pv-1rI3W_V8jmeORElbI7xRUm-V4xMmlvnKKzT7uNyQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);